### ISSUE TITLE
Decompile from stdin

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [intoolswetrust/jd-cli#64]
I am trying to decompile a class file from stdin. But it is not supported. Could you add support for taking the input from stdin?

```
$ java -jar jd-cli.jar /dev/stdin < /tmp/HelloWorld.class
21:04:08.334 INFO  com.github.kwart.jd.cli.Main - Decompiling /dev/stdin
21:04:08.345 ERROR com.github.kwart.jd.JavaDecompiler - Can't decompile /dev/stdin
org.jd.core.v1.service.deserializer.classfile.ClassFileFormatException: Invalid CLASS file
	at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadClassFile(ClassFileDeserializer.java:92)
	at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.innerLoadClassFile(ClassFileDeserializer.java:41)
	at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadClassFile(ClassFileDeserializer.java:28)
	at org.jd.core.v1.service.deserializer.classfile.DeserializeClassFileProcessor.process(DeserializeClassFileProcessor.java:27)
	at org.jd.core.v1.ClassFileToJavaSourceDecompiler.decompile(ClassFileToJavaSourceDecompiler.java:53)
	at org.jd.core.v1.ClassFileToJavaSourceDecompiler.decompile(ClassFileToJavaSourceDecompiler.java:38)
	at com.github.kwart.jd.JavaDecompiler.decompileClass(JavaDecompiler.java:59)
	at com.github.kwart.jd.input.ClassFileInput.decompile(ClassFileInput.java:63)
	at com.github.kwart.jd.cli.Main.main(Main.java:112)
null
```

**Comment by kwart** [comment]
use `-` instead as a filename to decompile from stdin.

For instance:
```
jd-cli - < Main.class
```
